# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-06 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_num_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=datetime.datetime(2018, 5, 6, 14, 36, 55, 855002, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
